### ISSUE TITLE
Some issues installing with pip

### ISSUE THREAD

**Issue by billzorn** [mightymercado/PySigmoid#10]
Attempting to install in a fresh virtual environment doesn't work for me. Here's what happens:

```
(.env) $ python -V
Python 3.6.4 :: Anaconda, Inc.
(.env) $ pip3 -V
pip 9.0.1 from .env/lib/python3.6/site-packages (python 3.6)
(.env) $ pip3 install PySigmoid
Collecting PySigmoid
  Using cached https://files.pythonhosted.org/packages/67/a6/2f2d896b9c5522598cd7d874d0d599e1ddf7307c51d60ef9f4c7d9e25c1c/PySigmoid-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/PySigmoid.egg-info
    writing pip-egg-info/PySigmoid.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/PySigmoid.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/PySigmoid.egg-info/requires.txt
    writing top-level names to pip-egg-info/PySigmoid.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/PySigmoid.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/PySigmoid.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/PySigmoid.egg-info/SOURCES.txt'
    running egg_info
    creating pip-egg-info/PySigmoid.Math.egg-info
    writing pip-egg-info/PySigmoid.Math.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/PySigmoid.Math.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/PySigmoid.Math.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/PySigmoid.Math.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'PySigmoid/Math' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xy0u9qyw/PySigmoid/
```

Downloading the repository and trying to install or run locally causes other issues:

```
(.env) $ pip3 install .
Processing ./PySigmoid
Collecting spfpm (from PySigmoid==0.3)
  Downloading https://files.pythonhosted.org/packages/d5/e1/1baf575dcfdce197d7a3eef0cf571ef628b0b56a51a409d67d4e434eb7bb/spfpm-1.4.tar.gz
Installing collected packages: spfpm, PySigmoid
  Running setup.py install for spfpm ... done
  Running setup.py install for PySigmoid ... done
Successfully installed PySigmoid-0.3 spfpm-1.4
(.env) $ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PySigmoid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./PySigmoid/PySigmoid/__init__.py", line 1, in <module>
    from .Posit import *
  File "./PySigmoid/PySigmoid/Posit.py", line 520, in <module>
    from .Quire import *
  File "./PySigmoid/PySigmoid/Quire.py", line 3, in <module>
    from .config import *
ModuleNotFoundError: No module named 'PySigmoid.config'
```

I was able to fix the issues and get an apparently working local install by commenting out the line at the beginning of Quire.py, as there doesn't seem to be a config module:

```
from .config import *
```

**Comment by mightymercado** [comment]
Fixed. Thank you.
