### ISSUE TITLE
Bug in fused operation

### ISSUE THREAD

**Issue by wswslzp** [mightymercado/PySigmoid#16]
When running the code below in Python 3.7.2:
```python
set_posit_env(8, 1)
a = Posit(2)
b = Posit(3)
c = Quire(0)
c.add_posit_product(a, b)
```
it reported an error like this:
```
Traceback (most recent call last):
  File "c:\Users\Liao Zhengpeng\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Liao Zhengpeng\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\Liao Zhengpeng\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\Liao Zhengpeng\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Liao Zhengpeng\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Liao Zhengpeng\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\lzp\Posit32-2-exact-multiply-accumulator-master\tb\posit_gen.py", line 61, in <module>
    c.add_posit_product(a, b)
  File "C:\Users\Liao Zhengpeng\AppData\Local\Programs\Python\Python37\lib\site-packages\PySigmoid\Quire.py", line 45, in add_posit_product
    self.q += Quire(p1) * Quire(p2)
  File "C:\Users\Liao Zhengpeng\AppData\Local\Programs\Python\Python37\lib\site-packages\FixedPoint.py", line 390, in __add__
    (self.scaledval + other.scaledval))
AttributeError: 'Quire' object has no attribute 'scaledval'
```
It shall be a bug right? Is there still someone maintaining this repo?

**Comment by wswslzp** [comment]
@mightymercado
